management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=post-service
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        default_schema: post-service
  data:
    redis:
      cluster:
        nodes: 127.0.0.1:7000,127.0.0.1:7001
      password: yourRedisPassword
      timeout: 5000
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
    mongodb:
      uri: mongodb://mongo:Aa%40123456@localhost:27017/k_product?authSource=admin

application:
  config:
    secret: Supper_Cat

kpro:
  security:
    enable: true
  storage:
    provider: minio # supported: none, minio, aws-s3
    endpoint: 'http://minio-api.kube-dev.io:6060'
    region: ap-southeast-1
    bucket: storage-public-dev-bucket
    credentials-access-key: T7DUNacoydsHT7r4
    credentials-secret-key: 8Kbm5eldS3NsG0oKpN3rXvaaCDGjpVFd
  origins: http://localhost:4200, http://localhost:3200